### ISSUE TITLE
Generar log para traza de errores en el programa

### ISSUE THREAD

**Issue by devIramos** [YordiKmh/ProyectoSistemasInvestigacion#2]
Hoy en día al ejecutar el programa, las exepciones se muestran en tiempo de ejecución y al cerrar el programa estas se pierden.
Se adjunta ejemplo:

<img width="716" alt="image" src="https://github.com/YordiKmh/ProyectoSistemasInvestigacion/assets/20213143/e3d533dd-a332-4cdb-9aa1-bc07fe538ce6">

Se requiere desarrollar la funcionalidad para que los errores de la aplicación puedan ser enviados a un archivo de texto .log, con el fin de poder realizar auditorias al funcionamiento del código.

Se adjunta ejemplo de como es necesario ver el archivo mencionado:
![codeimage-snippet_2](https://github.com/YordiKmh/ProyectoSistemasInvestigacion/assets/20213143/feb07c54-1606-4361-b662-d40987511555)

**Comment by YordiKmh** [comment]
[84a62cbc8c3d02f9bb5b18001ba88c9b31be7e1f](https://github.com/YordiKmh/ProyectoSistemasInvestigacion/commit/84a62cbc8c3d02f9bb5b18001ba88c9b31be7e1f)

Implementacion  de Archivo Log
